name: Alnuth
version: "4.0.2"
license: "GPL-2.0-or-later"
date: 2026-06-21
description: |
    ALgebraic NUmber THeory and an interface to PARI/GP and OSCAR

authors:
    - name: Björn Assmann
    - name: Andreas Distler
      url: mailto:a.distler@tu-bs.de
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.8"

needed-pkgs:
    - name: "polycyclic"
      version: ">=1.1"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/alnuth
readme: README.md
packageinfo: https://gap-packages.github.io/alnuth/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/alnuth/releases/download/v4.0.2/alnuth-4.0.2.tar.gz

abstract: |
    The <span class="pkgname">Alnuth</span> package provides various methods to compute with number fields which are given by a defining polynomial or by generators. Some of the methods provided in this package are written in <span class="pkgname">GAP</span> code. The other part of the methods is imported from an another computer algebra system, currently either PARI/GP or OSCAR. Hence this package contains some <span class="pkgname">GAP</span> functions and an interface to some functions in the computer algebra systems PARI/GP and OSCAR. The main methods included in <span class="pkgname">Alnuth</span> are: creating a number field, computing its maximal order (using the external CAS), computing its unit group (using the external CAS) and a presentation of this unit group, computing the elements of a given norm of the number field (using the external CAS), determining a presentation for a finitely generated multiplicative subgroup (using the external CAS), and factoring polynomials defined over number fields (using the external CAS).

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    algebraic number theory, number field, maximal order, interface to PARI/GP, interface to number theory in OSCAR, unit group, elements of given norm.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ADE26</span>]   <b class='BibAuthor'>Assmann, B., Distler, A. and Eick, B.</b>,
     <i class='BibTitle'>Alnuth, ALgebraic NUmber THeory and an interface to PARI/GP and OSCAR,
             Version 4.0.2</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/alnuth">https://gap-packages.github.io/alnuth</a></span>.
    </p>
    

bibtex: |
    @misc{ Alnuth,
      author =           {Assmann, B. and Distler, A. and Eick, B.},
      title =            {{Alnuth}, {ALgebraic NUmber THeory and an interface to
                          PARI/GP and OSCAR}, {V}ersion 4.0.2},
      month =            {Jun},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/alnuth}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{alnuth}}},
      keywords =         {algebraic  number theory; number field; maximal order;
                          interface  to  PARI/GP;  interface to number theory in
                          OSCAR; unit group; elements of given norm},
      printedkey =       {ADE26}
    }

