name: Alnuth
version: "3.2.1"
license: "GPL-2.0-or-later"
date: 2022-04-05
description: |
    Algebraic number theory and an interface to PARI/GP

authors:
    - name: Björn Assmann
    - name: Andreas Distler
      url: mailto:a.distler@tu-bs.de
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.8"

needed-pkgs:
    - name: "polycyclic"
      version: ">=1.1"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/alnuth
readme: README.md
packageinfo: https://gap-packages.github.io/alnuth/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/alnuth/releases/download/v3.2.1/alnuth-3.2.1.tar.gz

abstract: |
    The <span class="pkgname">Alnuth</span> package provides various methods to compute with number fields which are given by a defining polynomial or by generators. Some of the methods provided in this package are written in <span class="pkgname">GAP</span> code. The other part of the methods is imported from the computer algebra system PARI/GP. Hence this package contains some <span class="pkgname">GAP</span> functions and an interface to some functions in the computer algebra system PARI/GP. The main methods included in <span class="pkgname">Alnuth</span> are: creating a number field, computing its maximal order (using PARI/GP), computing its unit group (using PARI/GP) and a presentation of this unit group, computing the elements of a given norm of the number field (using PARI/GP), determining a presentation for a finitely generated multiplicative subgroup (using PARI/GP), and factoring polynomials defined over number fields (using PARI/GP).

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    algebraic number theory, number field, maximal order, interface to PARI/GP, unit group, elements of given norm.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ADET22</span>]   <b class='BibAuthor'>Assmann, B., Distler, A., Eick, B. and GAP Team, T.</b>,
     <i class='BibTitle'>Alnuth, Algebraic number theory and an interface to PARI/GP,
             Version 3.2.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/alnuth">https://gap-packages.github.io/alnuth</a></span>.
    </p>
    

bibtex: |
    @misc{ Alnuth3.2.1,
      author =           {Assmann, B. and Distler, A. and Eick, B. and GAP Team,
                          T.},
      title =            {{Alnuth},  Algebraic number theory and an interface to
                          PARI/GP, {V}ersion 3.2.1},
      month =            {Apr},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/alnuth}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{alnuth}}},
      keywords =         {algebraic  number theory; number field; maximal order;
                          interface  to  PARI/GP;  unit group; elements of given
                          norm},
      printedkey =       {ADET22}
    }

